import { Content, Category, AgeGroup } from '@/types';

export function getAgeGroupColor(ageGroup: AgeGroup): string {
  const colors = {
    baby: 'bg-pink-500',
    child: 'bg-blue-500',
    adult: 'bg-purple-500',
    family: 'bg-green-500',
  };
  return colors[ageGroup] || 'bg-gray-500';
}

export function getAgeGroupLabel(ageGroup: AgeGroup): string {
  const labels = {
    baby: 'Bebek (0-3)',
    child: 'Çocuk (4-8)',
    adult: 'Yetişkin (9+)',
    family: 'Aile',
  };
  return labels[ageGroup] || ageGroup;
}

export const mockContent: Content[] = [
  {
    id: '1',
    title: 'Subway Surfers',
    slug: 'subway-surfers',
    description: 'Dünyayı dolaş, engelleri aş ve en yüksek skoru yap! Renkli grafikler ve heyecan verici oynanış ile saatlerce eğlence.',
    instructions: '↑ Yukarı ok tuşu ile zıpla, ↓ Aşağı ok tuşu ile kay, ← → Sol/Sağ ok tuşları ile şerit değiştir.',
    content_type: 'game',
    age_group: 'child',
    category_id: 'cat-1',
    thumbnail_url: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500',
    content_url: 'https://example.com/games/subway-surfers',
    duration_minutes: 15,
    play_count: 125000,
    rating: 4.8,
    rating_count: 2450,
    is_premium: false,
    is_featured: true,
    published: true,
    meta_title: 'Subway Surfers - Ücretsiz Online Oyun',
    meta_description: 'Subway Surfers oyna, en yüksek skoru yap!',
    keywords: ['koşu', 'arcade', 'oyun'],
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
    created_by: null,
  },
  {
    id: '2',
    title: 'Renkli Balonlar',
    slug: 'renkli-balonlar',
    description: 'Balonları patlatarak renkleri öğren!',
    instructions: 'Balonlara tıkla ve patla!',
    content_type: 'game',
    age_group: 'baby',
    category_id: 'cat-2',
    thumbnail_url: 'https://images.pexels.com/photos/1058771/pexels-photo-1058771.jpeg?auto=compress&cs=tinysrgb&w=500',
    content_url: 'https://example.com/games/balloons',
    duration_minutes: 5,
    play_count: 45000,
    rating: 4.9,
    rating_count: 890,
    is_premium: false,
    is_featured: true,
    published: true,
    meta_title: null,
    meta_description: null,
    keywords: null,
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-01-20T00:00:00Z',
    created_by: null,
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Koşu Oyunları',
    slug: 'kosu',
    description: 'Heyecan verici koşu oyunları',
    age_group: 'child',
    icon_name: 'Zap',
    color_hex: '#f97316',
    content_count: 12,
    sort_order: 1,
    published: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Eğitici Oyunlar',
    slug: 'egitici',
    description: 'Öğrenirken eğlen',
    age_group: 'baby',
    icon_name: 'Brain',
    color_hex: '#3b82f6',
    content_count: 25,
    sort_order: 2,
    published: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Matematik',
    slug: 'matematik',
    description: 'Matematik oyunları',
    age_group: 'child',
    icon_name: 'Calculator',
    color_hex: '#10b981',
    content_count: 18,
    sort_order: 3,
    published: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Boyama',
    slug: 'boyama',
    description: 'Boyama oyunları',
    age_group: 'baby',
    icon_name: 'Palette',
    color_hex: '#8b5cf6',
    content_count: 30,
    sort_order: 4,
    published: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'Zeka Oyunları',
    slug: 'zeka',
    description: 'Zeka geliştiren oyunlar',
    age_group: 'adult',
    icon_name: 'Lightbulb',
    color_hex: '#f59e0b',
    content_count: 15,
    sort_order: 5,
    published: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];
