-- GameMonetize.com'dan 10 oyun ekle
-- Mevcut kategori ID'leri kullanılarak eklenecek

-- Kategori ID'leri (Platform Oyunları kullanılacak)
-- Platform Oyunları: ff43de0d-7a94-4ae6-8fff-9e36ea3c1c4b
-- Matematik Oyunları: 7cbcf228-5ee4-464d-bd43-8d0e8fe00dbd
-- Bulmaca: (bulmaca kategorisi)

-- Oyunları direkt ekle (GameMonetize iframe URL'leri ile)
-- İlk kategori ID'sini kullan (Platform Oyunları)
INSERT INTO content (title, slug, description, instructions, content_type, age_group, category_id, thumbnail_url, content_url, duration_minutes, is_premium, is_featured, published, meta_title, meta_description, keywords) VALUES
  ('Mud Offroad Jeep Game', 'mud-offroad-jeep-game', 'Çamurlu arazilerde off-road jeep sürüş deneyimi. Zorlu parkurları aş ve hedefe ulaş!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'child', 'ff43de0d-7a94-4ae6-8fff-9e36ea3c1c4b', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Mud Offroad Jeep Game - Ücretsiz Online Oyun', 'Çamurlu arazilerde off-road jeep sürüş deneyimi. Zorlu parkurları aş ve hedefe ulaş!', ARRAY['racing']),
  ('Epic Runner Parkour Game', 'epic-runner-parkour-game', 'Engelleri aşarak parkur becerilerinizi test edin. Hızlı koşun ve zıplayın!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'child', 'ff43de0d-7a94-4ae6-8fff-9e36ea3c1c4b', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Epic Runner Parkour Game - Ücretsiz Online Oyun', 'Engelleri aşarak parkur becerilerinizi test edin. Hızlı koşun ve zıplayın!', ARRAY['action']),
  ('Monster City', 'monster-city', 'Kendi canavar şehrinizi inşa edip yönetin. Şehir simülasyon oyunu!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'adult', 'ff43de0d-7a94-4ae6-8fff-9e36ea3c1c4b', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Monster City - Ücretsiz Online Oyun', 'Kendi canavar şehrinizi inşa edip yönetin. Şehir simülasyon oyunu!', ARRAY['strategy']),
  ('Jigsaw Adventure', 'jigsaw-adventure', 'Farklı zorluk seviyelerinde yapbozları tamamlayarak maceraya atılın.', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'child', '3a8adbde-474a-4f50-9930-73ddcd47c8bc', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Jigsaw Adventure - Ücretsiz Online Oyun', 'Farklı zorluk seviyelerinde yapbozları tamamlayarak maceraya atılın.', ARRAY['puzzle']),
  ('Confusions In Math 5-8', 'confusions-in-math-5-8', 'Matematik becerilerinizi sınayabileceğiniz eğlenceli bir bulmaca oyunu.', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'baby', '7cbcf228-5ee4-464d-bd43-8d0e8fe00dbd', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Confusions In Math 5-8 - Ücretsiz Online Oyun', 'Matematik becerilerinizi sınayabileceğiniz eğlenceli bir bulmaca oyunu.', ARRAY['educational']),
  ('Easiest Maths', 'easiest-maths', 'Basit matematik problemleriyle zihninizi çalıştırın. Eğitici oyun!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'baby', '7cbcf228-5ee4-464d-bd43-8d0e8fe00dbd', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Easiest Maths - Ücretsiz Online Oyun', 'Basit matematik problemleriyle zihninizi çalıştırın. Eğitici oyun!', ARRAY['educational']),
  ('Color Jam 3D', 'color-jam-3d', 'Renkleri birleştirerek bulmacaları çözebileceğiniz üç boyutlu bir oyun.', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'child', '3a8adbde-474a-4f50-9930-73ddcd47c8bc', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Color Jam 3D - Ücretsiz Online Oyun', 'Renkleri birleştirerek bulmacaları çözebileceğiniz üç boyutlu bir oyun.', ARRAY['puzzle']),
  ('Space IO', 'space-io', 'Uzayda geçen çok oyunculu bir strateji oyunu. En büyük ol!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'adult', '75518bf4-0974-4630-946b-5ad7c2308ebe', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Space IO - Ücretsiz Online Oyun', 'Uzayda geçen çok oyunculu bir strateji oyunu. En büyük ol!', ARRAY['strategy']),
  ('Pipe Connect Puzzle', 'pipe-connect-puzzle', 'Boru parçalarını doğru şekilde birleştirerek suyun akışını sağlayın.', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'child', '3a8adbde-474a-4f50-9930-73ddcd47c8bc', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Pipe Connect Puzzle - Ücretsiz Online Oyun', 'Boru parçalarını doğru şekilde birleştirerek suyun akışını sağlayın.', ARRAY['puzzle']),
  ('Cell Defense', 'cell-defense', 'Hücrelerinizi savunarak düşmanlara karşı mücadele edin. Strateji oyunu!', 'Oyunu oynamak için fare veya dokunmatik ekranı kullanın.', 'game', 'adult', 'aa450e8b-bb5e-4b6e-b5d2-feac0a1688f1', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://html5.gamemonetize.co/00f80f5f25tv7kjsr8z0az3ic2drfagu/', 15, false, false, true, 'Cell Defense - Ücretsiz Online Oyun', 'Hücrelerinizi savunarak düşmanlara karşı mücadele edin. Strateji oyunu!', ARRAY['strategy'])
ON CONFLICT (slug) DO NOTHING;

